project:
  type: website

website:
  title: "Technical Guides"
  image: images/logo_transp.png
  favicon: images/favicon.png
  open-graph: true
  google-analytics: "G-2PY6X92Q3P"
  comments:
    hypothesis: false
  back-to-top-navigation: true
  navbar:
    background: "#FFFFFF"
    foreground: "#3b66bc"
    logo: images/logo_transp.png
    logo-alt: "TASO logo"
    logo-href: https://taso-he.github.io/technicalguide/
    left:
      - icon: house
        href: index.qmd
        text: Home
    right: 
      - text: Sign up for our newsletter
        href: https://taso.org.uk/newsletter/
        icon: envelope
      - icon: github
        href: https://github.com/taso-he/technicalguide
      - icon: twitter
        href: https://twitter.com/taso_he
      - icon: linkedin
        href: https://uk.linkedin.com/company/taso

  sidebar: 
    - title: Guide
      style: floating
      background: "#edebe3"
      collapse-level: 1
      align: left
      contents:
        - href: index.qmd
          text: Introduction to the guides
        - section: "Data infrastructure guide"
          href: dig/index.qmd
          contents:
            - href: dig/index.qmd
              text: Introduction
            - href: dig/diagnose.qmd
              text: Diagnose
            - href: dig/plan.qmd
              text: "Plan: Research questions and outcomes"
            - href: dig/plan-methods.qmd
              text: "Plan: Choosing methods"
            - href: dig/plan-methods-overview.qmd
              text: "Plan: Methodology overview"              
            - href: dig/measure.qmd
              text: Measure
            - href: dig/reflect.qmd
              text: Reflect
            - href: dig/barriers.qmd
              text: Barriers and facilitators
            - href: dig/acknowledgements.qmd
              text: Acknowledgements 
        - section: "Data visualisation style guide"
          href: data-vis/index.qmd
          contents: 
            - href: data-vis/index.qmd
              text: Introduction
            - href: data-vis/principles.qmd
              text: Principles for good data visualisation
            - href: data-vis/styling.qmd
              text: Styling charts for TASO publications
            - href: data-vis/references.qmd
              text: References and further resources
        - section: "Coding good practice guide"
          href: coding-good-practice/index.qmd
          contents: 
            - href: coding-good-practice/index.qmd
              text: Introduction
            - href: coding-good-practice/good_practice.qmd
              text: Good practice tips
            - href: coding-good-practice/styler.qmd
              text: Automatic styling with styleR
            - href: coding-good-practice/furtherresources.qmd 
              text: Further resources
        - href: contact.qmd
          text: Contact point

  page-navigation: true

  page-footer:
    background: "#0f2847"
    foreground: "#FFFFFF"
    left: |
      TASO was set up by a consortium of King’s College London, Nottingham Trent University and the Behavioural Insights Team.  
      It is funded by the Office for Students and is an affiliate What Works Centre, and part of the UK Government’s What Works Movement.   
      Charity number: 1193025
    right:   |
      Contact us:  
      TASO  
      58 Victoria Embankment  
      Temple  
      London  
      EC4Y ODS  
      info@taso.org.uk
    center:
      - text: "EVENTS"
        href: https://taso.org.uk/events/
      - text: "TASO PRIVACY NOTICE"
        href: https://taso.org.uk/taso-privacy-notice/
      - text: "APPROPRIATE POLICY DOCUMENT"
        href: https://taso.org.uk/appropriate-policy-document/
      - text: "TASO SPEAKER REQUEST FORM"
        href: https://taso.org.uk/taso-speaker-request-form/
      - text: "ACCESSIBILITY STATEMENT"
        href: https://taso.org.uk/accessibility-statement/
    
  announcement: 
    icon: info-circle
    dismissable: true
    content: "This is a TASO resource site. Access the [main TASO website here](https://taso.org.uk/)"
    type: primary
    position: below-navbar
    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4
    toc-expand: true
    footnotes-hover: true
    code-fold: true
    code-summary: "Show the code"
    grid:
      sidebar-width: 200px
      body-width: 1000px
      margin-width: 200px
    link-external-newwindow: false
    fig-cap-location: top
    lightbox: true

editor: visual

execute:
  freeze: false

